name: "Setup Environment Variable"
description: "Setup Environment Variable Re-usable Github Action"
inputs:
  gh_head_ref:
    description: "GitHub Head Reference"
    required: true
  gh_ref_name:
    description: "GitHub Reference Name"
    required: true
  gh_event_repo_name:
    description: "GitHub Event Repository Name"
    required: true
  gh_sha:
    description: "Github SHA"
    required: true
  gh_repository:
    description: "Github Repository"
    required: true
  gh_run_number:
    description: "Github Run Number"
    required: true

outputs:
  short_sha:
    description: "Commit Short SHA"
    value: ${{ steps.env.outputs.short_sha }}
  chart_version:
    description: "Chart Version"
    value:  ${{ steps.env.outputs.chart_version }}
  image_version:
    description: "Image Version"
    value: ${{ steps.env.outputs.image_version }}
  image_tag:
    description: "Image Tag"
    value: ${{ steps.env.outputs.image_tag }}
  image_repo_tag:
    description: "Image Repository Tag"
    value: ${{ steps.env.outputs.image_repo_tag }}
  image_repository:
    description: "Image Repository"
    value: ${{ steps.env.outputs.image_repository }}
  registry:
    description: "Image Registry"
    value: ${{ steps.env.outputs.registry }}
  branch:
    description: "GitHub Branch"
    value: ${{ steps.env.outputs.branch }}
  compname:
    description: "Component Name"
    value: ${{ steps.env.outputs.compname }}
  dhurl:
    description: "DeployHub URL"
    value: ${{ steps.env.outputs.dhurl }}
  gh_handle:
    description: "GitHub Handle"
    value: ${{ steps.env.outputs.gh_handle }}

runs:
  using: "composite"
  steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      with:
        fetch-depth: 1

    - name: Export env
      id: env
      env:
        DHURL: https://console.deployhub.com
        REGISTRY: quay.io
        BRANCH: ${{ inputs.gh_head_ref || inputs.gh_ref_name }}
      shell: bash
      run: |
        BRANCH=$(echo "${{ env.BRANCH }}" | cut -d'/' -f1)
        BASE_VERSION=$(curl -s "https://ortelius.github.io/${{ inputs.gh_event_repo_name }}/index.yaml" | grep version: | awk '{print $2}' | cut -f1-2 -d. | sort -u -r --version-sort | head -1)
        SHORT_SHA=$(echo ${{ inputs.gh_sha }} | cut -c 1-6)
        {
          echo "dhurl=${{ env.DHURL }}"
          echo "branch=${BRANCH}"
          echo "chart_version=${BASE_VERSION}.${{ inputs.gh_run_number }}"
          echo "compname=${{ inputs.gh_event_repo_name }}"
          echo "image_repo_tag=${{ env.REGISTRY }}/${{ inputs.gh_repository }}:${BRANCH}-v${BASE_VERSION}.${{ inputs.gh_run_number }}-g${SHORT_SHA}"
          echo "image_repository=${{ env.REGISTRY }}/${{ inputs.gh_repository }}"
          echo "image_tag=${BRANCH}-v${BASE_VERSION}.${{ inputs.gh_run_number }}-g${SHORT_SHA}"
          echo "image_version=${BASE_VERSION}.${{ inputs.gh_run_number }}-g${SHORT_SHA}"
          echo "registry=${{ env.REGISTRY }}"
          echo "short_sha=${SHORT_SHA}"
          echo "gh_handle=$GITHUB_ACTOR"
        } >> "$GITHUB_OUTPUT"
